### ISSUE TITLE
Server struggles to serve many requests in HTTP2

### ISSUE THREAD

**Issue by hgwood** [antoinecellier/raccord#10]
Hitting the HTTP server with 100 requests throttled to "Good 3G" in Chrome takes about 1 second, mainly because of the 6-download limit of the browser. The server takes less than 100ms to respond to each request.

![image](https://cloud.githubusercontent.com/assets/1656170/18131427/1ac1f67e-6f93-11e6-9db1-f4a6ff8c5618.png)

Large grey bars means the browser is waiting to fire requests.

In HTTP2, it still takes 1 second (to my surprise). The browser send the 100 requests in parallel, but the server seems to have a hard time to respond quickly. The last request to fire is also the slowest: the server takes about 800ms to respond.

![image](https://cloud.githubusercontent.com/assets/1656170/18131455/3833651c-6f93-11e6-8fe3-deb330f3c828.png)

Large green bars means the browser is waiting for the server to respond.

Investigate why this is.

I guess the server is just not fast enough to handle all these concurrent requests, while a few request at a time in quick sequence is OK. But still, the server should be fast enough.

**Comment by jlandure** [comment]
Which server is used?

**Comment by hgwood** [comment]
Node.js + Express + node-spdy.

**Comment by hgwood** [comment]
I've run a new, simpler test. Here instead of using the `/rest/stations/:id` route and using the db, I hit `/` 100 times. This route is just `.get('/', (req, res) => res.send("It's working!"))`. The first 26 times, the server responds in less than 20ms. Then suddenly it slows down. The next 74 times, the server takes at least 80ms to respond.

![image](https://cloud.githubusercontent.com/assets/1656170/18135771/4e0d5cca-6fa3-11e6-9fc6-542e1dcb4064.png)

**Comment by hgwood** [comment]
Scratch that. Can't reproduce.

**Comment by hgwood** [comment]
Now that I think about it more, it must be normal behavior. The last request that the server responds to is sitting in the event loop queue while the others are processed, so from the browser's point of view it's slower, but the actual server work is not.

**Comment by hgwood** [comment]
Confirmed by measurements using `process.hrtime` with no db. All requests are processed in less than 1ms (well, the "business logic" part) without any slow down. Using the db it does slow down with each subsequent request, which is to be expected.
