### ISSUE TITLE
6éme besoin: faceting

### ISSUE THREAD

**Issue by antoinecellier** [antoinecellier/raccord#49]
- filtrée par une ligne (la ligne passe par tous les arrêts retournés) => 1 param facultatif
- filtrée par une recherche textuelle sur le nom (celle qu'on a déjà) => 1 param facultatif
- triée par rapport à la distance à la position de l'utilisateur => 2 param facultatif (latitude, longitude)
- filtrée par une distance maximum par rapport à la position de l'utilisateur => 1 param facultatif, valide seulement si la position est présente aussi
- filtrée par accès avec un fauteuil roulant.

**Comment by hgwood** [comment]
cf #50
